### ISSUE TITLE
deprecate _capt and _expr

### ISSUE THREAD

**Issue by twada** [twada/empower-core#1]
`_capt` and `_expr` is now out of date in the destructuring era.
Seeking for a better way without them.

see: [allow destructuring of `t` parameter. by jamestalmage · Pull Request #302 · sindresorhus/ava](https://github.com/sindresorhus/ava/pull/302#issuecomment-161933270)

**Comment by twada** [comment]
rough design

``` js
import assert from 'power-assert';
import _powerAssertCapture from 'power-assert-capturing';

assert(_powerAssertCapture(this, function (_capt) {
    return _capt(falsyStr, 'arguments/0');
}, {
    content: 'assert(falsyStr)',
    filepath: 'test/fixtures/Identifier/fixture.js',
    line: 3
}));
```

**Comment by jamestalmage** [comment]
race condition: https://github.com/power-assert-js/empower/issues/21#issuecomment-161940367

While yours looks better, it won't work with async/await:

``` js
async function foo() {
   function bar() {
     // await will not work in here.
   }
}
```

We could do

``` js
assert(await _powerAssertCapture(this, ...))
```

But then you end up having to change how you do things in `generators` vs `async functions` vs `synchronous` functions.

**Comment by twada** [comment]
closed since [Embed value capturing helper into transpiled code](https://github.com/power-assert-js/babel-plugin-espower/pull/11) has landed
