### ISSUE TITLE
onAssertion?

### ISSUE THREAD

**Issue by jamestalmage** [twada/empower-core#4]
See [this](https://github.com/jamestalmage/ava/blob/c1c5350f6d264bdaeba8bb3263a2d2125665279f/lib/test.js#L262-L266).

I am wondering if separate `onError` and `onSuccess` callbacks were the right call. Maybe it should have just been a single `onAssertion`? That would have worked better for my AVA implementation. I think it would have been simpler to implement on our end too.

We are still beta, so there is room to make this change.

**Comment by twada** [comment]
@jamestalmage Good point! Will be discussed in 0.3.0 milestone though :)

**Comment by jamestalmage** [comment]
> Will be discussed in 0.3.0 milestone though :)

Yep, I agree. Just putting it out there.

**Comment by sindresorhus** [comment]
Can we make a decision on this?

**Comment by twada** [comment]
@jamestalmage @sindresorhus I'm so sorry for delay.

I think separate `onError` and `onSuccess` callbacks were the right call.

We have only two real world example here,
- [ava/test.js at d6acdde056238d5e7403e63413b63a39dd61ff6a · sindresorhus/ava](https://github.com/sindresorhus/ava/blob/d6acdde056238d5e7403e63413b63a39dd61ff6a/lib/test.js#L286-L321)
- [empower/index.js at b1c222c9bbfa560fdf67f1cfd2b381ebc39cd8b7 · power-assert-js/empower](https://github.com/power-assert-js/empower/blob/b1c222c9bbfa560fdf67f1cfd2b381ebc39cd8b7/index.js#L34-L49)

AVA is using `onSuccess`, empower is not. I think
- want to distinguish error event type from success event type
- combine two things on the user side seems to be easier than providing one big event
- `onAssertion` is a bit ambiguous name, confusing whether the callback is called before or after the assertion.

How about you?

**Comment by jamestalmage** [comment]
I'm fine with it how it is. It's easy enough for us to coerce into a single event for AVA. If separate events make sense for your other uses, let's just table this.
